### ISSUE TITLE
[FEAT] 멋사 8차 과제🦁

### ISSUE THREAD

**Issue by bestlalala** [Likelion-at-SMWU-10th/LeeYeonSu#15]
## 📌  Feature Issue

코드라이언 '일단 만드는 Django' 강의 듣고 실습하기!

## 📝  To-do

- [x] 장고와 친해지기
- [x] Project 1: 회사 소개 페이지 만들기
- [x] Project 2: 개발자 대나무숲 만들기
- [x] Project 3: 영화 리뷰 사이트 만들기
